# Generated by Django 5.1.15 on 2026-10-02 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_paymentevent_subscription_gateway_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(db_index=True, max_length=64)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('report_type', models.CharField(choices=[('phishing', 'Phishing Link'), ('false_positive', 'False Positive'), ('suspicious', 'Suspicious Activity')], default='phishing', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed_phishing', 'Confirmed Threat'), ('false_positive', 'False Positive / Safe'), ('dismissed', 'Dismissed')], default='pending', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='accounts.organization')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrgPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('block', 'Block Dangerous Sites (Strict)'), ('warn', 'Warn Only')], default='block', max_length=20)),
                ('custom_allowlist', models.JSONField(blank=True, default=list, help_text='List of trusted domains')),
                ('custom_blocklist', models.JSONField(blank=True, default=list, help_text='List of blocked domains')),
                ('enforce_extension', models.BooleanField(default=True)),
                ('alert_webhook_url', models.URLField(blank=True, max_length=1024)),
                ('alert_email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='accounts.organization')),
            ],
        ),
    ]
