# Generated by Django 5.1.15 on 2026-10-02 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_incidentreport_orginvitation_orgpolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.IntegerField(default=90, help_text='Days to retain privacy-safe domain & hash scan logs before automated purge.')),
                ('auto_purge_enabled', models.BooleanField(default=True)),
                ('anonymize_on_purge', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention_policy', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SIEMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siem_type', models.CharField(choices=[('splunk_hec', 'Splunk HEC'), ('azure_sentinel', 'Microsoft Sentinel'), ('generic_webhook', 'Generic Webhook / Syslog'), ('datadog', 'Datadog Security')], default='generic_webhook', max_length=50)),
                ('endpoint_url', models.URLField(max_length=500)),
                ('auth_header_name', models.CharField(default='Authorization', max_length=100)),
                ('auth_token', models.CharField(blank=True, max_length=500)),
                ('min_severity', models.CharField(default='high', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_event_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siem_config', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SSOConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idp_entity_id', models.CharField(blank=True, max_length=255)),
                ('idp_sso_url', models.URLField(blank=True, max_length=500)),
                ('idp_x509_cert', models.TextField(blank=True)),
                ('enforce_sso_for_domain', models.CharField(blank=True, help_text='Domain to enforce SSO for, e.g. bankcorp.in', max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_config', to='accounts.organization')),
            ],
        ),
    ]
