# Generated by Django 5.2.14 on 2026-05-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_url', models.URLField(max_length=2048)),
                ('clean_url', models.URLField(max_length=2048)),
                ('domain', models.CharField(max_length=255)),
                ('verdict', models.CharField(max_length=30)),
                ('risk_level', models.CharField(max_length=30)),
                ('raw_phishing_probability', models.FloatField(default=0)),
                ('phishing_probability', models.FloatField(default=0)),
                ('legitimate_probability', models.FloatField(default=0)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
