# Generated by Django 5.1.15 on 2026-10-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatFeedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('openphish', 'OpenPhish'), ('urlhaus', 'URLhaus'), ('phishtank', 'PhishTank'), ('manual', 'Manual / Security Analyst')], default='openphish', max_length=50)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('url_hash', models.CharField(db_index=True, help_text='SHA-256 hash of malicious URL', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['domain', 'is_active'], name='scanner_thr_domain_55b00b_idx'), models.Index(fields=['url_hash', 'is_active'], name='scanner_thr_url_has_44b01d_idx')],
            },
        ),
    ]
